### ISSUE TITLE
view problem?

### ISSUE THREAD

**Issue by mk3d** [johnlui/SwiftNotice#1]
Dear developer, 
i have an issue with this notice.

I have a viewcontroller that open a new view.

In this second view, i want a "wait" notice between all view was loaded and retrived.
In the viewDidLoad(), i use  self.pleaseWait()
And when all item is loaded, i use self.clearAllNotice()

But, the notice appear on the first viewcontroller, not the second!?
Any idea?

Many thanks and best regards.

**Comment by johnlui** [comment]
the wait flag is on UIApplication.sharedApplication().keyWindow?.subviews.first as! UIView, maybe you can make your first and second view both as a child view of it.

**Comment by otapple** [comment]
貌似有个bug。
autoClear仅仅移除了UIview，而UIWindow还在，遮挡了keyWindow。
例如example中点击successNotice，noticeTop被遮挡，等3秒后autoClear，UIView被移除，但是UIWindow还在，因此noticeTop就无法点击
