### ISSUE TITLE
Application keep crashing in ios7

### ISSUE THREAD

**Issue by ravifullestop** [johnlui/SwiftNotice#10]
My application keep crashing in ios 7 on below line

static let rv = UIApplication.sharedApplication().keyWindow?.subviews.first as! UIView

when i have printed UIApplication.sharedApplication().keyWindow then it is showing nil. 

Please help.

**Comment by johnlui** [comment]
I just tested SwiftNotice on iOS 7 simulator with Xcode 6.4, it's OK.

Maybe you just call it before [window makeKeyAndVisible] called, so that the keyWindow is nil.

**Comment by ravifullestop** [comment]
I am working with swift and xcode 6.4 and it is crashing still

I have called  [window makeKeyAndVisible]  before not after

**Comment by johnlui** [comment]
forget to say that I tested https://github.com/johnlui/SwiftNotice/releases/tag/v3.1
