### ISSUE TITLE
device orientation layout problem (in landscape mode)

### ISSUE THREAD

**Issue by lyragosa** [johnlui/SwiftNotice#13]
it seems like that it still used the layout in portrait mode.
that is the preview image in the example project.

[Imgur](http://i.imgur.com/WuGi9uh.jpg?1)

build in OS X 10.11.1 ,XCode 7.0.1 , iOS 9.0

**Comment by johnlui** [comment]
yes, this is a problem on simulator. But it is OK on device, just try it.

**Comment by lyragosa** [comment]
hmmm i see it. thx.
