### ISSUE TITLE
UIStatusBarStyle color

### ISSUE THREAD

**Issue by lkqin** [johnlui/SwiftNotice#14]
at issues#3 use View controller-based status bar appearance-> no
but at ios9 xcode7 <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable in my debugger
how can i use the swiftnotic and change UIStatusBarStyle color

**Comment by johnlui** [comment]
I just created a new project with iOS9.1 SDK and run it in simulator and physical device. It's OK.

Actually this is not a issue of SwiftNotice, but a normal functional requirements.

**Comment by lkqin** [comment]
i am sorry the error is my Last Test Results ,I created a new project with iOS9.1 SDK The error is Disappear But The UIStatusBar is  Disappear too
how can i use the swiftnotic and make UIStatusBarStyle.LightContent
