### ISSUE TITLE
只要  SwiftNotice.showText(text) 等方法,  状态栏颜色就会变成黑色,  我应用状态栏是白色的

### ISSUE THREAD

**Issue by huerhai** [johnlui/SwiftNotice#15]

**Comment by johnlui** [comment]
感谢报告 bug，我将尽快检查解决~

**Comment by huerhai** [comment]
有没有检查出来呢~~  我也找了原因,没找到

**Comment by johnlui** [comment]
我刚刚把示例项目中的状态栏改成了白色，经过测试，并没有出现这个问题，要不你试试？

**Comment by huerhai** [comment]
我在plist文件里设置
View controller-based status bar appearance  ＝ NO

就没有我说的这个问题了,

**Comment by heeween** [comment]
我也遇到这个问题了 搞了好久.也是通过在plist文件里设置
View controller-based status bar appearance ＝ NO.
问题是因为swiftnotice用的都是window,window默认的状态栏颜色是黑色,所以在HUD显示的时候状态栏总是黑色的,当时swiftnotice clear之后才会显示我设置的白色.

现在都基于application来设置状态栏颜色 并且通过UIApplication.sharedApplication().setStatusBarHidden(false, withAnimation: .Fade)在加载程序启动页隐藏状态栏 然后在mainvc中显示出来 ,并且通过UIApplication.sharedApplication().setStatusBarStyle(.LightContent, animated: true)设置为白色
