### ISSUE TITLE
无法调整notice窗口的位置

### ISSUE THREAD

**Issue by iceman201** [johnlui/SwiftNotice#18]
无法调整notice窗口的位置， 在iPad app的master viewController中，位置特别奇怪，而且它显示的是歪的

![image](https://cloud.githubusercontent.com/assets/5027957/13235238/c43a32dc-da21-11e5-9ca4-a461718537c7.png)

**Comment by johnlui** [comment]
真机还是模拟器？

From My iPhone

**Comment by iceman201** [comment]
模拟器里

**Comment by johnlui** [comment]
文档第一句阐述了这个问题，模拟器里横屏也有问题，真机没问题。

From My iPhone
