### ISSUE TITLE
BUG:autoClear

### ISSUE THREAD

**Issue by otapple** [johnlui/SwiftNotice#2]
貌似有个bug。
autoClear仅仅移除了UIview，而UIWindow还在，遮挡了keyWindow。
例如example中点击successNotice，noticeTop被遮挡，等3秒后autoClear，UIView被移除，但是UIWindow还在，因此noticeTop就无法点击

**Comment by johnlui** [comment]
😱😱😱

**Comment by johnlui** [comment]
done!

**Comment by Doramical** [comment]
刚在引入的时候报错，这是提示
![7i1ct mdn0ta _hcf8 3xa0](https://cloud.githubusercontent.com/assets/9795720/11025894/8bd36136-86dc-11e5-9daf-e3cf5eb20a1c.jpg)

**Comment by johnlui** [comment]
这是模拟器呀，这个 bug 是偶发性的吗？

**Comment by Doramical** [comment]
刚回来真机测试又抱其他异常。
是我电脑的xcode的问题么？
