### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by lfarah** [johnlui/SwiftNotice#23]
I'd be cool to also add Cocoapods support. I done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).
Lemme know if you need any help! :smile:

**Comment by johnlui** [comment]
Sorry, with my own experience I do not suggest using CocoaPods in any pure Swift project, because pods is invaded.

**Comment by lfarah** [comment]
@johnlui I get it... I agree that Carthage is _better_, but most of the libraries I use only have _Cocoapods_ installation, so I end up using _CocoaPods_.
I loved your library and I'd be cool to have the option for CocoaPods installation

**Comment by Lucashuang0802** [comment]
@johnlui yeah, I think this is a great library. Providing as an option is always not a bad thing. I would love to help if you need any. 😃
