### ISSUE TITLE
Xcode7.3 调用任何一个方法都报错

### ISSUE THREAD

**Issue by linyc** [johnlui/SwiftNotice#28]
具体见下图
![image](https://cloud.githubusercontent.com/assets/1638896/14007346/c9c2d1b8-f1b0-11e5-9815-61609beb5bf0.png)

调试窗口输出：fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by johnlui** [comment]
7.3 这么坑，我试试。。。

**Comment by johnlui** [comment]
我测试了，自带的示例工程没有出现这个问题。建议你双重 clean 后重试。

**Comment by linyc** [comment]
"双重 clean"请问一下什么叫双重呢？

**Comment by linyc** [comment]
测出来了，原来是我放在viewDidLoad()里执行了，放个按钮，点击再执行就没问题
