### ISSUE TITLE
Spinner is behind the keyboard 

### ISSUE THREAD

**Issue by iceman201** [johnlui/SwiftNotice#31]
![image](https://cloud.githubusercontent.com/assets/5027957/15591238/dfe6ed64-23ef-11e6-913d-a1c08ab8bd2f.png)

**Comment by johnlui** [comment]
Thank you for your issue, sure I will fix it soon~

**Comment by johnlui** [comment]
Maybe this can solve this problem but I feel a little wired.

https://github.com/johnlui/SwiftNotice/blob/0b32a1098a6a7989a37d05c5f47bf15d636e0e7c/SwiftNotice.swift#L115

**Comment by iceman201** [comment]
haha awesome, never mind I just setup when spinner spinning then hide keyboard.
