### ISSUE TITLE
Device Orientation

### ISSUE THREAD

**Issue by nick2687** [johnlui/SwiftNotice#4]
It seems that when you attempt to use this with an app in landscape mode, the notification is displayed sideways (for portrait orientation)

Any ideas on how to make this work both in landscape and portrait?

**Comment by johnlui** [comment]
sorry about seeing your issue now.

yes SwiftNotice is not supporting orientation now. I tried but it seems there are lots of things to do.

**Comment by johnlui** [comment]
:smile:  with the support of reveal, i will make SwiftNotice support orientation soon.

**Comment by johnlui** [comment]
SwiftNotice supports both landscape and portrait now.
