### ISSUE TITLE
XCODE8 兼容性改进

### ISSUE THREAD

**Issue by ynmaoyong** [johnlui/SwiftNotice#41]
timer.setTimer 在XCODE8 中已经废弃，编译报错。可以替换为下面的代码：timer.scheduleRepeating(deadline: DispatchTime.now(), interval: .milliseconds(timeInterval), leeway: .milliseconds(1))

**Comment by johnlui** [comment]
前几天我把手头的项目迁移到 Swift3 的时候就解决了，稍后我会更新~
