### ISSUE TITLE
此插件有五处错误

### ISSUE THREAD

**Issue by tangtang520** [johnlui/SwiftNotice#6]
62 115 143 181 195行 望及时改正

**Comment by johnlui** [comment]
Notice: https://github.com/johnlui/SwiftNotice#requirements

**Comment by tangtang520** [comment]
下载之后导入工程 编译报五处错误

**Comment by johnlui** [comment]
## Requirements
- iOS 7.0+
- Xcode 6.3 (Swift 1.2) in v3.1
- Xcode 7 (Swift 2.0) in the current master branch
