### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ymcao** [johnlui/SwiftNotice#7]
if let window = sender as? UIWindow {
            if let index = windows.IndexOf({ (item) -> Bool in
                return item == window
            }) {
                windows.removeAtIndex(index)
            }
        }
提示 indexof这个方法找不到 ？

**Comment by johnlui** [comment]
Notice：https://github.com/johnlui/SwiftNotice#requirements

## Requirements
- iOS 7.0+
- Xcode 6.3 (Swift 1.2) in v3.1
- Xcode 7 (Swift 2.0) in the current master branch
