### ISSUE TITLE
在 Xcode6.4中使用会有错误

### ISSUE THREAD

**Issue by aqlxt746** [johnlui/SwiftNotice#8]
在196行出现错误

SwiftNotice.swift:196:28: 'Array<UIWindow>' does not have a member named 'indexOf'

**Comment by johnlui** [comment]
Xcode 6.4 是一个奇葩的版本，我记得有两处 API 修改从 6.3 改过了之后到了 Xcode 7 又改回 6.3了。

都是 Swift 核心类操作语法的细微修改，自己根据提示改了便是。

**Comment by ravifullestop** [comment]
Tell me what to do for fix this. And please write in english

**Comment by johnlui** [comment]
I make SwiftNotice support Xcode 7 in the master branch, so we can't go back.

It is very easy to make it support Xcode 6.4: just follow messages Xcode show, they are all tiny api changes.

**Comment by johnlui** [comment]
Xcode 6.4 support: https://github.com/johnlui/SwiftNotice/issues/9
